apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database
spec:
  selector:
    matchLabels:
      app: mysql-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-database
    spec:
      containers:
      - name: mysql-database
        image: mysql:8.0.29-debian
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-volume
        persistentVolumeClaim:
          claimName: mysql-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-database
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce